/** Auto-generated by scripts/rebuild_sprites.py - do not edit. */
import f00 from './sprites/run_00.png'
import f01 from './sprites/run_01.png'
import f02 from './sprites/run_02.png'
import f03 from './sprites/run_03.png'
import f04 from './sprites/run_04.png'
import f05 from './sprites/run_05.png'
import f06 from './sprites/run_06.png'
import f07 from './sprites/run_07.png'
import f08 from './sprites/run_08.png'
import f09 from './sprites/run_09.png'
import f10 from './sprites/run_10.png'
import f11 from './sprites/run_11.png'
import f12 from './sprites/run_12.png'
import f13 from './sprites/run_13.png'
import f14 from './sprites/run_14.png'

export const FRAMES = [f00, f01, f02, f03, f04, f05, f06, f07, f08, f09, f10, f11, f12, f13, f14]
