/** Auto-generated by scripts/rebuild_sprites.py - do not edit. */
export const SPRITE_W = 177
export const SPRITE_H = 120
export const FRAME_COUNT = 15
export const CYCLE_HZ = 2
export type HeadAnchor = { hx: number; hy: number; cup: number }
export const HEAD_ANCHORS: HeadAnchor[] = []
export const BAKED = true
